# ?? ?? ??
server.port=10414

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.auto_quote_keyword=true
#spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.defer-datasource-initialization=true

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.transaction.interceptor=trace

toss.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  # test_sk_XZYkKL4Mrj10Wz7kA0EBV0zJwlEW