server.port=10407

spring.application.name=order-service

### JPA Setting
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=test
spring.datasource.password=1234
spring.datasource.dbcp2.connection-init-sqls=SELECT 1

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.auto_quote_keyword=true



### Order Setting
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
logging.level.org.hibernate.type=trace

### Cloud ????
spring.cloud.config.enabled=false
eureka.client.enabled=false

toss.secret-key=${TOSS_KEY}